# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "FASTQC_MULTIQC_ANALYSIS"
description: Generates comprehensive quality control reports for sequencing data
keywords:
  - quality control
  - fastqc
  - multiqc
  - qc
  - sequencing
components:
  - FASTQC
  - MULTIQC
input:
  - fastq_files:
      type: file
      description: Input FASTQ files for quality control analysis
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
output:
  - fastqc_report:
      type: file
      description: FastQC HTML reports for each input file
      pattern: "*.html"
  - multiqc_report:
      type: file
      description: Aggregated MultiQC HTML report
      pattern: "multiqc_report.html"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Lupphes"
maintainers:
  - "@Lupphes"
