repository_type: pipeline

nf_core_version: 3.2.0

lint: 
  plugin_includes: False

template:
  org: nf-core
  name: eukavarizer
  description: Structural Variance for Eukaryotic Genomes
  author: Ondřej Sloup
  version: 1.1.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
