repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: eukavarizer
  description: Structural Variance for Eukaryotic Genomes
  author: Ondrej Sloup
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
