apiVersion: v1
kind: Pod
metadata:
  name: pvc-uploader
  namespace: sloup-ns
spec:
  containers:
    - name: uploader
      image: busybox
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: storage
          mountPath: /mnt/launch
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: eukavarizer
  restartPolicy: Never
