name: "vcf_repgen"
description: "Generates an HTML report from a merged VCF file, individual VCF files, and SURVIVOR analysis."
keywords:
  - vcf
  - report
  - survivor
  - visualization
input:
  - merged_vcf:
      type: file
      description: "Merged VCF file"
      pattern: "*.vcf"
  - other_vcfs:
      type: file
      description: "List of individual VCF files for comparison"
      pattern: "*.vcf"
  - survivor_vcf:
      type: file
      description: "SURVIVOR merged VCF file"
      pattern: "*.vcf"
  - survivor_stats:
      type: file
      description: "SURVIVOR stats table"
      pattern: "*.tsv"
  - taxonomy_id:
      type: string
      description: "Sample taxonomy ID"
  - outdir:
      type: file
      description: "Output directory for reports"
output:
  - report_html:
      type: file
      description: "Generated HTML report"
      pattern: "*.html"
authors:
  - name: "Ondřej Sloup"
    email: "ondrej.sloup@protonmail.com"
    github: "Lupphes"
    affiliation: "MUNI"
